### ISSUE TITLE
Offer_v2's businessId is nil when fetched via hotspots

### ISSUE THREAD

**Issue by lozhuf** [shopgun/tjek-swift-sdk#44]
This means that hotspots are failing to load in the new SDK. To discuss with @mekanixdk - may well be a server fix.

**Comment by mortenbo** [comment]
Our hotspot model is an "offer lite" version: https://squid-api.tjek.com/v2/catalogs/_iy7FNym/hotspots

We only cherry pick often used elements. I would, personally, like to get rid of all of this metadata and just expose the offer ID. Then it's up to the clients to fetch the offers and get the real model.

**Comment by lozhuf** [comment]
ahhh, interesting... I think it's still useful to have some metadata about the offer (speeds up interactions with the publication greatly). Also lots of clients are relying on this data, so we can't just get rid of it. The best approach is to add a new 'HotspotOffer' model.

**Comment by mekanixdk** [comment]
So, is this a "bug" I need to address, or will this turn into a feature request?

**Comment by lozhuf** [comment]
@mekanixdk no, I think this is just a confusion over what model is returned by the hotspots endpoint. No changes needed on your side.
